version: '3.8'

services:
  server:
    build:
      context: ..
      dockerfile: docker/server.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///instance/malaria_lab.db
      - UPLOAD_FOLDER=uploads
      - SECRET_KEY=your-secret-key-here
      - JWT_SECRET_KEY=your-jwt-secret-key-here
    volumes:
      - ../server/instance:/app/instance
      - ../server/uploads:/app/uploads
      - ../server/logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
